version: '3.8'

secrets:
  auth_users:
    file: ./secrets/auth-users.txt

services:
  api:
    build: .
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${API_DOMAIN_NAME}`)
      - traefik.http.services.api.loadbalancer.server.port=8080
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=letsencrypt
  traefik:
    image: traefik:${TRAEFIK_IMAGE_VERSION:-latest}
    command:
      ## Global
      - --api.dashboard=true
      ## Docker
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      ## Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      ## Certificates
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    # We add the usage of secrets for Basic Auth
    secrets:
      - auth_users
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## Middlewares
      - traefik.http.middlewares.basic-auth.basicauth.usersFile=/run/secrets/auth_users
      ## HTTPS
      - traefik.http.routers.traefik-https.entrypoints=websecure
      - traefik.http.routers.traefik-https.rule=Host(`${TRAEFIK_DOMAIN_NAME}`)
      - traefik.http.routers.traefik-https.service=api@internal
      - traefik.http.routers.traefik-https.middlewares=basic-auth
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-https.tls.certresolver=letsencrypt