version: '3.8'

secrets:
  auth_users:
    file: ./secrets/auth-users.txt

networks:
  traefik:
    name: traefik

services:
  api:
    build: .
    ports:
      - "8080:443"
    labels:
      - traefik.http.routers.api.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls=true
      - traefik.http.services.api.loadbalancer.server.port=8080

  traefik:
    image: traefik:${TRAEFIK_IMAGE_VERSION:-latest}
    command:
      ## Global
      - --log.level=DEBUG
      - --api.dashboard=false
      ## Docker
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      ## Entrypoints
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      ## Certificates
      # We add Let's Encrypt as a default certificate resolver
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "443:443"
    # We add the usage of secrets for Basic Auth
    secrets:
      - auth_users
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## Middlewares
      # We add a Basic Auth middleware using the users defined in the Docker secret
      - traefik.http.middlewares.basic-auth.basicauth.usersFile=/run/secrets/auth_users
      # We add a middleware to redirect HTTP to HTTPS
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true