version: '3.8'

secrets:
  auth_users:
    file: ./secrets/auth-users.txt

services:
  reelremarks:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reelremarks.rule=Host(`127.0.0.1`)"  # Replace with your actual domain
      - "traefik.http.routers.reelremarks.entrypoints=web"
      - "traefik.http.routers.reelremarks.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/secrets/auth-users.txt"
    expose:
      - "8080"

networks:
  traefik:
    external: true